### ISSUE TITLE
Spike: does Slang replace glslang + SPIRV-Cross for us? (D11's gate)

### ISSUE THREAD

**Issue by andy-emerson** [andy-emerson/love.wasm#62]
**Closed 2026-08-16 — the decision it gated was re-ruled, so the spike no longer gates anything.**

This was D11's gate: a four-step spike, cheapest-killer-first, asking whether Slang could replace glslang + SPIRV-Cross with GLSL kept as the authoring language.

**D11 was re-ruled on 2026-08-16: LÖVE's dialect becomes a dialect of WGSL.** Slang is not in the chosen path, so the spike has nothing left to decide.

**One thing recorded honestly, because the ruling was made on a bad argument from the Agent.** The case put against Slang was that it is a different language and would break every existing LÖVE shader. That describes the superseded record's **Option C** — "replace GLSL with Slang as the authoring language" — which that record had already rejected for exactly that reason. **Option B, the one this spike was gating, kept GLSL and used Slang only as the compiler.** The objection did not apply to the option on the table.

The Human reviewed that and let the ruling stand. It is noted in D11 so that anyone revisiting it does so against the option actually on offer, not the one the Agent described.

**What was worth keeping from this issue has moved into the durable record**, rather than being lost with it:

- glslang is not merely a compiler here, it is LÖVE's **reflection system** — the backend-independent `graphics/Shader.cpp` includes glslang's *internal* headers and walks its AST (`getBaseType`, line 1038) to build LÖVE's `DataFormat`/`DataBaseType` descriptors for every backend.
- Spike step (2) — *does the reflection API expose what `Shader.cpp:1238–1531` needs: uniform formats, block layouts, std430 packing, storage-texture formats, storage-buffer structure?* — is the live form of **Q2**, which now gates the WebGPU backend under D11's ruling instead.

Full records: [`wasi/DECISIONS.md`](../blob/main/wasi/DECISIONS.md) D11 (with the superseded record kept in full) and Q2.

**Comment by andy-emerson** [comment]
## Spike results, tests 1–2 (slangc v2026.14.1 prebuilt, linux-x86_64)

**Test material:** 19 unique generated shaders captured from a real corpus run at the GL seam — a page-side tap on `WebGL2RenderingContext.prototype.shaderSource` during the corpus, so this is LÖVE's actual output (preamble, injected uniforms, `#define`-heavy dialect wrappers, `#line` directives), not hand-picked samples. Zero engine changes to capture.

### Test 1 — GLSL acceptance: **PASS, 19/19 to SPIR-V, after a one-character fix in LÖVE's own wrapper**

First run: 7/19. Every one of the 12 failures was the **same single cause**: `error[E30027]: 'st' is not a member of 'vector<float,4>'` — Slang's GLSL mode does not implement GLSL's `stpq` swizzle set. The `.st` is not in user code; it is in LÖVE's generated pixel-main wrapper, **`Shader.cpp:313`**:

```cpp
love_PixelColor = effect(VaryingColor, MainTex, VaryingTexCoord.st, love_PixelCoord);
```

With `.st` → `.xy` (identical semantics) in that one generated line: **19/19 compile to SPIR-V**. Two caveats, both ours to control: `-D__VERSION__=300 -DGL_ES` must be predefined (Slang's preprocessor does not define GLSL's builtins; LÖVE owns the preamble and can inject equivalents), and stage + `-entry main` must be stated explicitly.

### WGSL target — experimental, confirmed experimentally: 9/19

Two distinct causes, both Slang-upstream, neither in our shaders:

1. **A capability-annotation gap, not a codegen gap.** All matrix-using shaders fail `E36107: unavailable features in entry point`. Bisected to GLSL-mode matrix `operator*`. In `source/slang/glsl.meta.slang:226–271` every matrix-multiply overload is annotated `[require(cpp_cuda_glsl_hlsl_spirv_llvm, sm_4_0_version)]` — **`wgsl` is simply absent from the target list**, while the bodies are plain `mul()`, which the WGSL backend handles fine (verified with a pure-Slang control). A one-line-per-overload upstream fix.
2. **Compiler segfaults** on 4 of the 19 (all three vertex shaders + one fragment) when targeting WGSL.

Consistent with the issue's prior: the WGSL backend (~2,400 lines) is young. Does not affect D10 phase 1 (hand-written WGSL), and does not affect the D11 core promise (replacing glslang+SPIRV-Cross on the SPIR-V/validation/reflection paths), which is what 19/19 answers.

### Test 2 — reflection: **PASS on the whole checked surface**

`-reflection-json` on the real captured shaders plus a synthetic UBO/SSBO/storage-image shader, against the `Shader.cpp:1238–1531` needs:

| needed | result |
|---|---|
| scalar base types | `float32` / `int32` / etc., explicit |
| vector/matrix shape | element counts, `4x4` rows×cols |
| uniform offsets/sizes/strides | exact — `love_UniformsPerDraw`: offset 0, size 192, stride 16 |
| std140 block layout | exact (mat4 @0 sz64, vec3 @64 sz12, float @76, int @80) |
| SSBO | recognized as `shaderStorageBuffer`, structure reflected |
| storage-image format | `"format": "rgba8"` in JSON; C++ API has `getBindingRangeImageFormat` + full `SlangImageFormat` enum |

### Test 3 — in progress

Host-stage generators building now (trimmed configure accepted all the flags: GFX/SLANGD/SLANGI/SLANGRT/REPLAYER/DXIL off, LLVM disabled). wasi target stage next; will report the first wall if there is one.

**Provisional read:** the two cheap killers did not fire. The GLSL-acceptance risk collapsed to one swizzle family — in text we generate — and reflection is complete for our surface. The open risks are now exactly the ones test 3 exists to find, plus the known immaturity of the WGSL backend, which phase-1 D10 does not depend on.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by andy-emerson** [comment]
## Spike complete — all four tests ran. Three pass; the fourth is the problem.

### Test 3 — wasm32-wasi build: **PASS, with a small enumerated patch set**

The two-stage CMake flow worked as designed: host `all-generators` (8 tools, including the `slang-embed`/`slang-bootstrap` core-module pipeline), then the target stage with `wasi/toolchain/Platform/WASI.cmake` + the wasi-eh sysroot + `SLANG_GENERATORS_PATH`. **338 TUs compiled; `libslang-compiler.a` produced; a smoke binary links and RUNS under node:wasi** — `slang_createGlobalSession2` with `enableGLSL`, which loads the embedded core module (the deepest init path), exits 0.

Every wall, in order, none touching compiler logic:

1. **Platform detection** — `slang.h:121` `#error unknown target platform`. Slang already has `SLANG_WASM`, keyed only on `__EMSCRIPTEN__`. Fix: `|| defined(__wasi__)`. One line, plainly upstreamable.
2. **`std::mutex`/`std::thread`** — libc++ threads-off keeps `lock_guard` but omits the lockables. Fixed with a ~70-line force-included stub (single-thread no-op locks; `std::thread` ctor traps — its only user is the child-process I/O pump, unreachable where processes don't exist). This is exactly what Emscripten's libc++ ships built-in; ours removes the headers instead.
3. **`dlfcn.h`** — absent on wasi (and the include leaked to host glibc's, a hermeticity smell in our flags worth fixing regardless). 15-line stub; every load fails cleanly; correct because all dlopen'd plugin backends are disabled.
4. **wasi-libc surface gaps** — `mkstemp`, `chmod`, `umask`, `realpath`. Four inline stubs. A sweep of `source/core` found **no fork/exec/pipe anywhere** — process spawning is isolated in one file.
5. **`std::filesystem::relative`** — one call site (`slang-io.cpp` `getRelativePath`), which already documents a fallback (return the input path); guarded to take it under `__wasi__`.
6. **`slang-unix-process.cpp`** — compiled out whole under `__wasi__`; 6 reachable `Process` statics (clock, escape handler, suffix, failing `create`, no-op sleep) + `__cxa_thread_atexit` provided in a ~30-line stub TU.
7. Build-time only: 8 shallow submodules (`unordered_dense`, `miniz`, `lz4`, `spirv-headers`, `cmark`, `vulkan` headers, `fast_float`, `lua` — for `slang-fiddle`, of all things).

Per the failure-mode framing: this is **stub-layer territory, not fork territory**. Items 1 and 5 are one-line upstream PRs; the rest is a shim TU + headers we'd own, ~120 lines total, analogous to our existing WASI preview1 shim.

### Test 4 — size: **FAIL at face value, and this is now D11's central problem**

| artifact | bytes |
|---|---|
| smoke.wasm, trimmed config, MinSizeRel, `--gc-sections`, stripped | **23 MB** |
| `love-game.wasm` today — ALL of LÖVE + glslang + everything | **7.9 MB** |

The trimmed, garbage-collected Slang compiler alone is **~3× our entire current artifact**. The CMake trim flags cut only ~3% of source (the heavy exclusions — DXC, LLVM — were fetched binaries that never entered the build anyway), and `--gc-sections` cannot collect the big remainder: the embedded core module (34,671 lines of `hlsl.meta.slang` serialized as data) plus a type-checker/IR/emit pipeline reached through dynamic dispatch.

Mitigations unmeasured: brotli (~3–4× on wasm, so ~6–8 MB wire), `wasm-opt -Oz`, `SLANG_ENABLE_VALIDATION_VM_BYTECODE=OFF`, a non-embedded core module (conflicts with #7's one-artifact rule). None plausibly reaches glslang's current contribution.

### Where this leaves D11

Tests 1–3 say Slang *works*: 19/19 of LÖVE's real generated shaders to SPIR-V after a one-character fix in our own wrapper, reflection complete for the `Shader.cpp` surface, and a clean wasi port with a ~120-line shim. Test 4 says the cost lands on every player's download, tripling it.

Options for the Human's re-ruling, since D11's own reopen clause ("trimmed compiled size exceeds what glslang costs today") has fired:

- **A. Accept the size.** ~23 MB raw / ~6–8 MB wire buys one toolchain, direct WGSL, public reflection API.
- **B. Slang only where it pays: per-game.** #7's packager links Slang only for games that call `newShader`; shader-less games ship without any shader compiler at all (glslang currently rides along for everyone). Composes with D10 phase 1 (six hand-written WGSL standard shaders need no compiler).
- **C. Keep glslang+SPIRV-Cross; add Tint for WGSL when D10 phase 2 needs it.** The pre-D11 status quo; three toolchains, but each smaller.
- **D. Defer**: D10 phase 1 needs no translator at all, so nothing blocks on this today.

All spike artifacts (captured shaders, stub headers, build scripts, logs) are in the session scratchpad; the method is fully recorded above and in the prior comment for re-running against a future Slang release — the WGSL backend is where their work is currently landing.

---
_Generated by [Claude Code](https://claude.ai/code)_
